---
- name: Install 2 ovs+ovn builds and upgrade db from one to the other
  hosts: local
  connection: local
  # remote_user: root
  remote_user: vagrant
  # become: yes
  become_method: sudo
  roles:
    ## - common   FIXME
    - build

